"""initial tables: drivers, sessions, laps, intervals, race_summaries

Revision ID: fd2cac4365b3
Revises: 
Create Date: 2026-02-09 17:28:58.894499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2cac4365b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('driver_number', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('team_name', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('driver_number')
    )
    op.create_table('intervals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=True),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('gap_to_leader', sa.String(length=20), nullable=True),
    sa.Column('interval', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervals_driver_number'), 'intervals', ['driver_number'], unique=False)
    op.create_index(op.f('ix_intervals_session_key'), 'intervals', ['session_key'], unique=False)
    op.create_table('laps',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=True),
    sa.Column('driver_number', sa.Integer(), nullable=True),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('is_pit_out_lap', sa.Boolean(), nullable=True),
    sa.Column('stint', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laps_driver_number'), 'laps', ['driver_number'], unique=False)
    op.create_index(op.f('ix_laps_session_key'), 'laps', ['session_key'], unique=False)
    op.create_table('race_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_key', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_race_summaries_session_key'), 'race_summaries', ['session_key'], unique=False)
    op.create_table('sessions',
    sa.Column('session_key', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=50), nullable=True),
    sa.Column('circuit_short_name', sa.String(length=50), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('session_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_index(op.f('ix_race_summaries_session_key'), table_name='race_summaries')
    op.drop_table('race_summaries')
    op.drop_index(op.f('ix_laps_session_key'), table_name='laps')
    op.drop_index(op.f('ix_laps_driver_number'), table_name='laps')
    op.drop_table('laps')
    op.drop_index(op.f('ix_intervals_session_key'), table_name='intervals')
    op.drop_index(op.f('ix_intervals_driver_number'), table_name='intervals')
    op.drop_table('intervals')
    op.drop_table('drivers')
    # ### end Alembic commands ###
